apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: rx7pkjugp-go 
  janus-idp.io/tekton: rx7pkjugp-go
  backstage.io/kubernetes-id: rx7pkjugp-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rx7pkjugp-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  