apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: rx7pkjugp-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jsmid/rhtap-qe:1db933272830610866f0ac5439ba47f7cb756cea@sha256:d51e2985b298c9ddb5fb37c5d0f43eb0f1a2c982c2d81b4300d800b9fd0dc578
          name: container-image
